# @name tokenacc
###
POST http://localhost:3000/auth/registrar
Content-Type: application/json

{
  "usuario": "bryann",
  "senha": "bryann0510"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "usuario": "bryann",
  "senha": "bryann0510"
}
###
POST http://localhost:3000/proprietarios
Content-Type: application/json

{
  "cpf": "12244678909",
  "nome": "Camargo",
  "telefone": "47995568293"
}

###
GET http://localhost:3000/proprietarios
Content-Type: application/json

###
POST http://localhost:3000/veiculos
Content-Type: application/json

{
  "placa": "JKD3987",
  "modelo": "Ferrari",
  "preco": 800000,
  "cpfProprietario": "12244678909"
}

###
GET http://localhost:3000/veiculos

###
GET http://localhost:3000/veiculos/proprietarios/12244678901

###
GET http://localhost:3000/veiculos/tipo/Luxo

### 
PUT http://localhost:3000/veiculos/JKD3987
Content-Type: application/json

{
  "modelo": "Corsa"
}